- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  roles:
    - {role: git, tags: ['git']}
    - {role: package_manager, tags: ['bootstrap']}
    - {role: bash, tags: ['bootstrap', 'bash']}
    - {role: zsh, tags: ['bootstrap', 'zsh']}
    - {role: fish, tags: ['bootstrap', 'fish']}
    - {role: vim, tags: ['vim']}
    - {role: kota65535.rbenv, tags: ['bootstrap', 'rbenv']}
    - {role: ruby, tags: ['ruby']}
    - {role: rubymine, tags: ['rubymine']}
    - {role: golang, tags: ['golang']}
    - {role: uu, tags: ['uu']}
#    - {role: python, tags: ['python']}
#    - {role: npm, tags: ['npm']}
    - {role: ag, tags: ['ag']}
    - {role: fzf, tags: ['fzf']}
    - {role: tmux, tags: ['tmux']}
#    - {role: git-flow, tags: ['git-flow']}
    - {role: karabiner, when: ansible_os_family == "Darwin"}
    - {role: hammerspoon, when: ansible_os_family == "Darwin"}
    - {role: chunkwm, when: ansible_os_family == "Darwin", tags: ['bootstrap', 'chunkwm']}
    - {role: sublime, when: ansible_os_family == "Darwin"}
    - {role: osx, when: ansible_os_family == "Darwin", tags: ['bootstrap']}
    - {role: wine, when: ansible_os_family == "Darwin", tags: ['bootstrap']}
    - {role: geerlingguy.mas, when: ansible_os_family == "Darwin", tags: ['bootstrap']}
