
# Installation and setup
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"
- include: osx.yml
  when: ansible_os_family == "Darwin"

- name: Ensure zsh is in /etc/shells
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'
    state: present

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- include: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto

- name: Prepare .zsh.before dir for pre-init hooks
  file:
    path: "{{dotfiles_user_home}}/.zshrc.before"
    state: directory

- name: Prepare .zsh.after dir for post-init hooks
  file:
    path: "{{dotfiles_user_home}}/.zshrc.after"
    state: directory
