
# Prezto
- name: Install prezto
  script: install_prezto.sh creates="{{ '~/.zprezto' | expanduser}}"

- name: Link zpreztorc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zpreztorc.link"
    dest: "{{ '~/.zpreztorc' | expanduser }}"
    state: link

- name: Link zshrc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc.link"
    dest: "{{ '~/.zshrc' | expanduser }}"
    state: link

- name: Prepare zsh.prompts dir
  file:
    path: "{{ dotfiles_user_home }}/.zsh.prompts"
    state: directory

- name: Get Garrett prompt
  get_url:
    url: https://github.com/chauncey-garrett/zsh-prompt-garrett/raw/master/prompt_garrett_setup
    dest: "{{ dotfiles_user_home }}/.zsh.prompts/prompt_garrett_setup"
