
- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes

- name: Check if gitconfig exists
  stat: path="{{dotfiles_user_home}}/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "{{dotfiles_user_home}}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "{{dotfiles_user_home}}/.gitconfig"

- name: Link git template dir
  file:
    src: "{{ dotfiles_home }}/roles/git/files/git_template.link"
    dest: "{{ dotfiles_user_home }}/.git_template"
    state: link
    force: yes

- name: Link git commit message template
  file:
    src: "{{ dotfiles_home }}/roles/git/files/git_commit_msg.txt"
    dest: "{{ dotfiles_user_home }}/.git_commit_msg.txt"
    state: link
