# Installation
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"
- include: osx.yml
  when: ansible_os_family == "Darwin"

# Plugin manager
- name: Makes sure autoload directory exists
  file: path="{{dotfiles_user_home}}/.vim/autoload" state=directory

# Configuration
- name: Check if config/nvim exists
  stat: path="{{dotfiles_user_home}}/.config/nvim"
  register: config_nvim_stat
  failed_when: False

- name: Backup config/nvim
  command: mv ~/.config/nvim ~/.config/nvim.bak
  args:
    creates: "{{dotfiles_user_home}}/.config/nvim.bak"
  when: config_nvim_stat.stat.exists

- name: Config config dir
  file:
    path: "{{dotfiles_user_home}}/.config"
    state: directory

- name: Symlink config/nvim
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/nvim.link"
    dest: "{{dotfiles_user_home}}/.config/nvim"
    state: link

- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ dotfiles_user_home }}/.config/nvim/init.vim"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link
  when: create_vimrc_symlink

- name: Install plugins
  command: nvim +PlugInstall +qall
  when: vim_install_plugins
