# ~/.tmuxinator/c3-server.yml

name: c3-server
root: ~/code/work/git/uu_cloudg01_c3-server-ruby/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t c3-server

windows:
  - cmd: cd uu_c3-cmd && nvim .
  - controller: cd uuapps && nvim .
  - docker:
      layout: main-vertical
      panes:
        - cd docker && nvim .
        - cd docker
  - appbox:
      layout: main-horizontal
      panes:
        - cd uu_c3-appbox && nvim uu_c3-uuapp-deploy.json
        - cd uu_c3-appbox
