#!/bin/bash

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Hack Nerd Font:Bold:12.0"
yabai -m config status_bar_icon_font         "Hack Nerd Font:Regular:12.0"
yabai -m config status_bar_background_color  0xe0202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# specific space settings
yabai -m config --space 3 layout             float
yabai -m config --space 4 layout             float
yabai -m config --space 7 layout             float

# window rules
yabai -m rule --add app=Spotify space=3
yabai -m rule --add app=Spark space=3
yabai -m rule --add app=Adium space=4 manage=off
yabai -m rule --add app="Microsoft To Do" space=4 grid=1:3:0:0:2:1
yabai -m rule --add app=Todoist space=4 grid=1:3:0:0:2:1
yabai -m rule --add app=Toggl space=4 grid=1:3:2:0:1:1
yabai -m rule --add app=Steam space=7
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Předvolby systému$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app=Things manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
